In [10]:
# Write a program to distinguish between Array Indexing and Fancy Indexing.
import numpy as np
arr1=np.array([1,2,3,4])
print("\nArray Indexing is:",arr1[0])
print("\nFancy Indexing",arr1[[0,1,2]])


Array Indexing is: 1

Fancy Indexing [1 2 3]


In [28]:
# Execute the 2D array Slicing.
import numpy as np
arr=np.random.rand(2,2)
print(arr)
print("\n")
print(arr[0][0:1])
print("\n")
print(arr[0:2][0:2])

[[0.81872352 0.92871774]
 [0.27799817 0.7100481 ]]


[0.81872352]


[[0.81872352 0.92871774]
 [0.27799817 0.7100481 ]]


In [42]:
# Create the 5-Dimensional arrays using ‘ndmin’.
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [32]:
# Reshape the array from 1-D to 2-D array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

na = arr.reshape(3, 3)

print(na)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
# Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)
print("stack function",arr)
arr = np.hstack((arr1, arr2))
print("hstack function",arr)
arr = np.vstack((arr1, arr2))
print("vstack function",arr)
arr = np.dstack((arr1, arr2))
print("dstack function",arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [40]:
# Perform the searchsort method in Numpy array.
import numpy as np

arr = np.array([6, 8, 9,7])

x = np.searchsorted(arr, 7,side='left')

print(x)

1


In [43]:
# Create Numpy Structured array using your domain features.
import numpy as np
std_info = np.array([('Koushik Das', 23, 55.0), ('KD', 23, 59.0)],
       dtype=[('std_name', (np.str_, 10)), ('std_age', np.int32), ('std_weight', np.float64)])
 
print(std_info)

[('Koushik Da', 23, 55.) ('KD', 23, 59.)]


In [56]:
# Create Data frame using List and Dictionary.
import pandas as pd
arr1=np.array([[1,2,3,4],[5,6,7,8]])
df1=pd.DataFrame(arr1)
print(df1)

print("\n")

arr2=np.array([1,2,3,4,5])
df2=pd.DataFrame(arr2)
print(df2)

arr3={"One":"Koushik","Two":"KD","Three":"Sanu"}
df3=pd.DataFrame(arr3,index=["One","Two","Three"])
print(df3)

   0  1  2  3
0  1  2  3  4
1  5  6  7  8


   0
0  1
1  2
2  3
3  4
4  5
           One Two Three
One    Koushik  KD  Sanu
Two    Koushik  KD  Sanu
Three  Koushik  KD  Sanu


In [13]:
# Create Data frame on your Domain area and perform the following operations to find and eliminate the missing data from the dataset.
import pandas as pd
r=pd.read_csv("./Student_Portal_dataset.csv")

print(r)

df=r.isnull()
print(df)

df=r.notnull()
print(df)

df=r.dropna()
print(df)

df=r.fillna("Hello KD")
print(df)

df=r.replace("Hello KD","KD")
print(df)

      Student_ID Semster_Name     Paper_ID Paper_Name  Marks
0    SID20131143        Sem_1  SEMI0012995    Paper 1   44.0
1    SID20131143        Sem_1  SEMI0015183    Paper 2   74.0
2            NaN          NaN          NaN        NaN    NaN
3    SID20131143        Sem_1  SEMI0015910    Paper 4   44.0
4    SID20131143        Sem_1  SEMI0016208    Paper 5   95.0
..           ...          ...          ...        ...    ...
244  SID20131177        Sem_4  SEMI0044518    Paper 6   56.0
245  SID20131177        Sem_4  SEMI0044275    Paper 7   80.0
246  SID20131177        Sem_5  SEMI0058693    Paper 2   83.0
247  SID20131177        Sem_5  SEMI0056942    Paper 3   53.0
248  SID20131177        Sem_5  SEMI0055343    Paper 4   93.0

[249 rows x 5 columns]
     Student_ID  Semster_Name  Paper_ID  Paper_Name  Marks
0         False         False     False       False  False
1         False         False     False       False  False
2          True          True      True        True   True
3       

In [18]:
# Q10. Perform the Hierarchical Indexing in the above created dataset.
import pandas as pd
r=pd.read_csv("./Student_Portal_dataset.csv")
# a=r.set_index(["Student_ID","Semster_Name","Paper_ID","Paper_Name","Marks"])
a=r.set_index(["Marks","Student_ID"])
print(a)

                  Semster_Name     Paper_ID Paper_Name
Marks Student_ID                                      
44.0  SID20131143        Sem_1  SEMI0012995    Paper 1
74.0  SID20131143        Sem_1  SEMI0015183    Paper 2
NaN   NaN                  NaN          NaN        NaN
44.0  SID20131143        Sem_1  SEMI0015910    Paper 4
95.0  SID20131143        Sem_1  SEMI0016208    Paper 5
...                        ...          ...        ...
56.0  SID20131177        Sem_4  SEMI0044518    Paper 6
80.0  SID20131177        Sem_4  SEMI0044275    Paper 7
83.0  SID20131177        Sem_5  SEMI0058693    Paper 2
53.0  SID20131177        Sem_5  SEMI0056942    Paper 3
93.0  SID20131177        Sem_5  SEMI0055343    Paper 4

[249 rows x 3 columns]
